"use client";
import Link from "@/components/site-link";
import {useEffect,useState,useMemo} from "react";
import {ArrowUpRight,ChevronUp,Search,X} from "lucide-react";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {useDiscoveryTool} from "./webmcp";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {useStartupBackend} from '@/hooks/use-startup-backend';
import {SignInDialog} from '@/components/startup-account';
import {LiveVisitors} from '@/components/live-visitors';
import {StartupLogo} from '@/components/startup-logo';
import {InfinityLoop,InlineLoader} from '@/components/infinity-loop';
import {startupCategories} from '@/lib/startup-schema';
const demoStartups=[
 {slug:"nova",name:"NOVA",pitch:"Smarter deliveries. Stronger local businesses.",story:"A delivery co-pilot for independent retailers. NOVA brings orders, route planning and customer updates into one simple workspace, helping small shops spend less time coordinating deliveries and more time growing their businesses.",category:"Mobility",city:"Cape Town",stage:"Launched",year:2026,founder:"Thandi & Sipho",votes:[32,284,641,910],move:12,age:3,mark:"N",color:"#dfff81",ink:"#253416"},
 {slug:"pocketwise",name:"Pocketwise",pitch:"Make your money make sense.",story:"A calmer way for young South Africans to understand their spending. Pocketwise turns everyday transactions into clear budgets and practical savings goals, with a focus on the realities of irregular income.",category:"Fintech",city:"Johannesburg",stage:"Revenue",year:2025,founder:"Lebo Mokoena",votes:[40,236,780,1240],move:7,age:12,mark:"p.",color:"#ece3ff",ink:"#6940a9"},
 {slug:"soko",name:"Soko",pitch:"Your neighbourhood market, one tap away.",story:"A digital storefront for neighbourhood sellers. Soko makes it easy to browse local products, place orders and discover independent businesses in your community.",category:"Commerce",city:"Durban",stage:"Launched",year:2026,founder:"Aisha & Lunga",votes:[24,198,420,540],move:5,age:5,mark:"s",color:"#ffe2c8",ink:"#bf5b24"},
 {slug:"sungrid",name:"Sungrid",pitch:"A brighter way to manage your energy.",story:"Simple energy insights for homes and small businesses. Sungrid helps people understand their solar generation, battery use and grid consumption in one place.",category:"Climate / Energy",city:"Stellenbosch",stage:"Building",year:2026,founder:"Pieter Jacobs",votes:[18,172,390,460],move:9,age:6,mark:"☀",color:"#fff0b8",ink:"#9a7312"},
 {slug:"lumalearn",name:"Luma Learn",pitch:"Big futures start with a little curiosity.",story:"Bite-sized learning designed around the South African classroom. Luma Learn gives learners guided practice and clear explanations they can access from a phone.",category:"Education",city:"Pretoria",stage:"Launched",year:2025,founder:"Naledi Dube",votes:[16,149,460,790],move:3,age:18,mark:"lu",color:"#d8e9ff",ink:"#355b9d"},
 {slug:"justnow",name:"JustNow",pitch:"Less admin. More of the work you love.",story:"One tidy place for freelancers to organise projects, send invoices and keep track of client work. Built with independent South African businesses in mind.",category:"SaaS",city:"Cape Town",stage:"Revenue",year:2025,founder:"Alex Williams",votes:[22,126,500,1050],move:4,age:10,mark:"jn",color:"#ffe0e5",ink:"#9f4560"},
 {slug:"veld",name:"Veld",pitch:"Better decisions, from the ground up.",story:"Practical crop planning for small farms. Veld helps growers keep field records, organise seasonal tasks and make sense of farm observations.",category:"AgriTech",city:"Bloemfontein",stage:"Building",year:2026,founder:"Mpho Molefe",votes:[12,104,220,260],move:6,age:4,mark:"v",color:"#d9ead5",ink:"#497343"},
 {slug:"askizwi",name:"Ask Izwi",pitch:"AI that speaks your language.",story:"A multilingual assistant exploring everyday questions in local languages. Ask Izwi is an early prototype built to make digital tools more approachable.",category:"AI",city:"Johannesburg",stage:"Building",year:2026,founder:"Zanele Nkosi",votes:[27,88,190,220],move:15,age:1,mark:"i*",color:"#e6e2fd",ink:"#5b4a98"}
];
type Startup=typeof demoStartups[number]&{id?:string;website?:string;country?:string|null;myVote?:boolean;logo_path?:string|null};
function Mark({s,small=false}:{s:Startup;small?:boolean}){return <span className={`mark ${small?"small":""}`} style={{background:s.color,color:s.ink}}>{s.logo_path?<StartupLogo id={s.id} name={s.name} hasLogo/>:s.mark}</span>}
export default function Home(){
 const backend=useStartupBackend();const navigate=(path:string)=>location.assign(new URL(path,location.origin).href);
 const [now,setNow]=useState(0);useEffect(()=>{queueMicrotask(()=>setNow(Date.now()))},[]);
 const [authOpen,setAuthOpen]=useState(false),[pendingVote,setPendingVote]=useState<string|null>(null);
 const startups=useMemo<Startup[]>(()=>backend.status==='demo'?demoStartups.map(s=>({...s,country:'South Africa'})):backend.records.map(s=>({id:s.id,logo_path:s.logo_path,slug:s.slug,name:s.name,website:s.website,pitch:s.pitch,story:s.story,category:s.category,city:s.city,country:s.country,stage:s.stage,year:s.founded_year,founder:s.founder,votes:[s.today_votes,s.week_votes,s.month_votes,s.total_votes],myVote:s.my_vote,move:0,age:Math.max(0,Math.floor((now-Date.parse(s.published_at))/86400000)),mark:s.name.slice(0,2),color:'#e5edd8',ink:'#36512e'})),[backend.status,backend.records,now]);
 const [category,setCategory]=useState("All startups"),[period,setPeriod]=useState("3"),[query,setQuery]=useState(""),[city,setCity]=useState("all"),[view,setView]=useState("ranked"),[votes,setVotes]=useState<string[]>([]),[notice,setNotice]=useState("");
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem("startup-sa-demo-votes")||"[]");if(Array.isArray(v))queueMicrotask(()=>setVotes(v.filter(x=>typeof x==="string")));}catch{}},[]);
 useEffect(()=>{const slug=new URLSearchParams(location.search).get("startup");if(slug)location.replace('/startups/'+encodeURIComponent(slug))},[]);
 useDiscoveryTool(setQuery,setCategory,setCity,setView);
 const hasVoted=(s:Startup)=>s.id?!!s.myVote:votes.includes(s.slug);
 const count=(s:Startup)=>s.votes[Number(period)]+(!s.id&&votes.includes(s.slug)?1:0);
 const shown=startups.filter(s=>(category==="All startups"||s.category===category)&&(city==="all"||s.city===city)&&(view!=="new"||s.age<=7)&&`${s.name} ${s.pitch} ${s.category} ${s.city} ${s.country??""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>view==="new"?a.age-b.age:count(b)-count(a));
 async function vote(s:Startup){
   if(s.id){if(!backend.client||pendingVote||backend.status!=='ready')return;setPendingVote(s.id);try{await backend.vote(s.id,!s.myVote)}catch(e){toast.error(e&&typeof e==='object'&&'message' in e?String(e.message):'Your vote could not be saved. Please retry.')}finally{setPendingVote(null)}return}
   const next=votes.includes(s.slug)?votes.filter(x=>x!==s.slug):[...votes,s.slug];setVotes(next);try{localStorage.setItem("startup-sa-demo-votes",JSON.stringify(next))}catch{setNotice("Vote applied for this visit. Device storage is unavailable.")}
 }
 function profile(s:Startup|null){if(s)navigate('/startups/'+encodeURIComponent(s.slug))}
 function openSubmit(){if(backend.status==='loading')return;if(backend.status==='error'){toast.error('Please retry the connection before submitting.');return}navigate('/submit');}
 return <div className="shell"><header><Link className="brand" href="/" aria-label="StartupsAfrica home"><img src="/startupsa-logo.png" alt=""/><span>StartupsAfrica</span></Link><span className="beta">EARLY ACCESS</span><nav aria-label="Main navigation"><Link href="/how-it-works">How it works</Link></nav><button className="secondary" onClick={()=>backend.session?navigate(backend.moderator?'/admin':'/account'):setAuthOpen(true)}>{backend.session?backend.moderator?'Admin':'My account':'Sign in'}</button></header>
 <main><section className="intro"><h1>Discover Africa’s next generation of startups.</h1><p>Find emerging companies, new launches and founders worth watching — before everyone knows them.</p><div className="intro-actions"><button className="primary" disabled={backend.status==='loading'} onClick={openSubmit}>{backend.status==='loading'?<><InfinityLoop className="button-loader" aria-hidden="true"/> Connecting…</>:<>Put your startup on the map <ArrowUpRight size={17}/></>}</button></div></section>
 <div className="board-layout"><section aria-label="Startup leaderboard"><div className="board-heading"><div><h2>{view==="new"?"Fresh off the launchpad":category==="All startups"?"The ones to watch":category}</h2><p>{view==="new"?"New ideas. Meet the latest arrivals.":"Good ideas deserve a head start."}</p></div><LiveVisitors client={backend.client}/></div>
 <div className="board-controls"><Tabs value={period} onValueChange={setPeriod}><TabsList aria-label="Ranking time period">{[{label:"All time",value:"3"},{label:"Today",value:"0"}].map(({label,value})=><TabsTrigger key={value} value={value}>{label}</TabsTrigger>)}</TabsList></Tabs></div>
 <div className="filters"><label className="search"><Search size={17}/><input aria-label="Search startups" placeholder="Search startups, ideas, or countries…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="search-clear" aria-label="Clear search" onClick={()=>setQuery("")}><X size={14}/></button>}</label><Select value={category} onValueChange={setCategory}><SelectTrigger className="category-filter-trigger" aria-label="Filter by category"><SelectValue/></SelectTrigger><SelectContent className="category-filter-menu" position="popper" align="end" sideOffset={4} collisionPadding={12}><SelectItem value="All startups">All categories</SelectItem>{[...startupCategories].sort().map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div>
 {backend.status==='loading'&&<p className="connection-message"><InlineLoader label="Loading startups…"/></p>}{backend.status==='error'&&<div role="alert" className="connection-message"><p>{backend.error}</p><button className="secondary" onClick={()=>backend.client?backend.reload():location.reload()}>Retry connection</button></div>}<div className="startup-list">{backend.status!=='error'&&shown.map((s,i)=><article key={s.slug} className={`startup-row rank-${i+1}`}><span className="rank">{String(i+1).padStart(2,"0")}</span><a className="profile-open" aria-label={`View ${s.name} profile`} href={`/startups/${encodeURIComponent(s.slug)}`}><Mark s={s}/><span className="startup-info"><span className="startup-title">{s.name}{s.age<=3&&<span className="new-badge">NEW</span>}</span><span className="pitch">{s.pitch}</span><span className="metadata"><span>{s.category}</span><b>·</b>{s.city}{s.country&&<><b>·</b>{s.country}</>}{!s.id&&<><b>·</b><span className="movement">↗ {s.move}</span></>}</span></span></a><button disabled={!!pendingVote} className={`vote ${hasVoted(s)?"voted":""}`} aria-label={`${hasVoted(s)?"Remove vote for":"Upvote"} ${s.name}`} aria-pressed={hasVoted(s)} onClick={()=>vote(s)}><ChevronUp size={19}/><strong>{count(s)}</strong></button></article>)}</div>
 {!shown.length&&['demo','ready'].includes(backend.status)&&<div className="empty"><Search size={28}/><h3>{startups.length?'No startups found':'Be the first on the board.'}</h3><p>{startups.length?'Try another idea, category or city.':'Submit your startup. Approved listings will appear here.'}</p><button className="secondary" onClick={()=>{if(!startups.length){openSubmit();return}setQuery("");setCategory("All startups");setCity("all");setView("ranked")}}>{startups.length?'Clear filters':'Submit your startup'}</button></div>}</section>
 <aside className="advertise-card"><span className="advertise-kicker">GROW YOUR REACH</span><h2>Advertise your business here</h2><p>Put your brand in front of people discovering Africa’s next big ideas.</p><a href="mailto:hello@startups.summit88.co.za">Get in touch <ArrowUpRight size={16}/></a></aside></div></main>
 <section className="sponsor-credit" aria-label="Built and sponsored by Summit88"><span>Built and Sponsored by</span><a href="https://www.summit88.co.za" target="_blank" rel="noopener noreferrer" aria-label="Visit Summit88"><img src="/summit88-logo.png" alt="Summit88" width="600" height="106"/></a></section>
 <footer><Link className="brand" href="/" aria-label="StartupsAfrica home"><img src="/startupsa-logo.png" alt=""/><span>StartupsAfrica</span></Link><p>Discover Africa’s next generation of startups.</p><Link href="/how-it-works">About & rules <ArrowUpRight size={14}/></Link></footer>


 <SignInDialog open={authOpen} onOpenChange={setAuthOpen} client={backend.client}/>
 <Toaster theme="light" position="bottom-center" closeButton/><Notification message={notice} clear={()=>setNotice("")}/></div>
}
function Notification({message,clear}:{message:string;clear:()=>void}){useEffect(()=>{if(message){toast(message);clear()}},[message,clear]);return null}
