"use client";
import {useEffect,useState,useMemo,useRef} from "react";
import {ArrowUpRight,ArrowRight,ChevronUp,Search,Trophy,Sparkles,MapPin,Globe,Plus,Zap,Heart,Code2,Leaf,GraduationCap,ShoppingBag,Check,X} from "lucide-react";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {useDiscoveryTool} from "./webmcp";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {useStartupBackend} from '@/hooks/use-startup-backend';
import {submissionSchema} from '@/lib/startup-schema';
import {SignInDialog,AccountDialog} from '@/components/startup-account';
const categories=["All startups","Fintech","AI","SaaS","Climate / Energy","Health","Education","Commerce","Mobility","AgriTech","Developer Tools","Other"];
const icons=[Globe,Zap,Sparkles,Code2,Leaf,Heart,GraduationCap,ShoppingBag,ArrowRight,Leaf,Code2,Plus];
const demoStartups=[
 {slug:"nova",name:"NOVA",pitch:"Smarter deliveries. Stronger local businesses.",story:"A delivery co-pilot for independent retailers. NOVA brings orders, route planning and customer updates into one simple workspace, helping small shops spend less time coordinating deliveries and more time growing their businesses.",category:"Mobility",city:"Cape Town",stage:"Launched",year:2026,founder:"Thandi & Sipho",votes:[32,284,641,910],move:12,age:3,mark:"N",color:"#dfff81",ink:"#253416"},
 {slug:"pocketwise",name:"Pocketwise",pitch:"Make your money make sense.",story:"A calmer way for young South Africans to understand their spending. Pocketwise turns everyday transactions into clear budgets and practical savings goals, with a focus on the realities of irregular income.",category:"Fintech",city:"Johannesburg",stage:"Revenue",year:2025,founder:"Lebo Mokoena",votes:[40,236,780,1240],move:7,age:12,mark:"p.",color:"#ece3ff",ink:"#6940a9"},
 {slug:"soko",name:"Soko",pitch:"Your neighbourhood market, one tap away.",story:"A digital storefront for neighbourhood sellers. Soko makes it easy to browse local products, place orders and discover independent businesses in your community.",category:"Commerce",city:"Durban",stage:"Launched",year:2026,founder:"Aisha & Lunga",votes:[24,198,420,540],move:5,age:5,mark:"s",color:"#ffe2c8",ink:"#bf5b24"},
 {slug:"sungrid",name:"Sungrid",pitch:"A brighter way to manage your energy.",story:"Simple energy insights for homes and small businesses. Sungrid helps people understand their solar generation, battery use and grid consumption in one place.",category:"Climate / Energy",city:"Stellenbosch",stage:"Building",year:2026,founder:"Pieter Jacobs",votes:[18,172,390,460],move:9,age:6,mark:"☀",color:"#fff0b8",ink:"#9a7312"},
 {slug:"lumalearn",name:"Luma Learn",pitch:"Big futures start with a little curiosity.",story:"Bite-sized learning designed around the South African classroom. Luma Learn gives learners guided practice and clear explanations they can access from a phone.",category:"Education",city:"Pretoria",stage:"Launched",year:2025,founder:"Naledi Dube",votes:[16,149,460,790],move:3,age:18,mark:"lu",color:"#d8e9ff",ink:"#355b9d"},
 {slug:"justnow",name:"JustNow",pitch:"Less admin. More of the work you love.",story:"One tidy place for freelancers to organise projects, send invoices and keep track of client work. Built with independent South African businesses in mind.",category:"SaaS",city:"Cape Town",stage:"Revenue",year:2025,founder:"Alex Williams",votes:[22,126,500,1050],move:4,age:10,mark:"jn",color:"#ffe0e5",ink:"#9f4560"},
 {slug:"veld",name:"Veld",pitch:"Better decisions, from the ground up.",story:"Practical crop planning for small farms. Veld helps growers keep field records, organise seasonal tasks and make sense of farm observations.",category:"AgriTech",city:"Bloemfontein",stage:"Building",year:2026,founder:"Mpho Molefe",votes:[12,104,220,260],move:6,age:4,mark:"v",color:"#d9ead5",ink:"#497343"},
 {slug:"askizwi",name:"Ask Izwi",pitch:"AI that speaks your language.",story:"A multilingual assistant exploring everyday questions in local languages. Ask Izwi is an early prototype built to make digital tools more approachable.",category:"AI",city:"Johannesburg",stage:"Building",year:2026,founder:"Zanele Nkosi",votes:[27,88,190,220],move:15,age:1,mark:"i*",color:"#e6e2fd",ink:"#5b4a98"}
];
type Startup=typeof demoStartups[number]&{id?:string;website?:string;myVote?:boolean};
const emptyDraft={name:"",website:"",pitch:"",category:"",city:"",stage:"",founder:"",year:"2026",story:""};
function Mark({s,small=false}:{s:Startup;small?:boolean}){return <span className={`mark ${small?"small":""}`} style={{background:s.color,color:s.ink}}>{s.mark}</span>}
export default function Home(){
 const backend=useStartupBackend();
 const [authOpen,setAuthOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[pendingVote,setPendingVote]=useState<string|null>(null),[sending,setSending]=useState(false);
 const submissionRequest=useRef<{id:string;body:string}|null>(null);
 const startups=useMemo<Startup[]>(()=>backend.status==='demo'?demoStartups:backend.records.map(s=>({id:s.id,slug:s.slug,name:s.name,website:s.website,pitch:s.pitch,story:s.story,category:s.category,city:s.city,stage:s.stage,year:s.founded_year,founder:s.founder,votes:[s.today_votes,s.week_votes,s.month_votes,s.total_votes],myVote:s.my_vote,move:0,age:Math.max(0,Math.floor((Date.now()-Date.parse(s.published_at))/86400000)),mark:s.name.slice(0,2),color:'#e5edd8',ink:'#36512e'})),[backend.status,backend.records]);
 const [category,setCategory]=useState("All startups"),[period,setPeriod]=useState("1"),[query,setQuery]=useState(""),[city,setCity]=useState("all"),[view,setView]=useState("ranked"),[votes,setVotes]=useState<string[]>([]),[selected,setSelected]=useState<Startup|null>(null),[submit,setSubmit]=useState(false),[rules,setRules]=useState(false),[saved,setSaved]=useState(false),[notice,setNotice]=useState(""),[draft,setDraft]=useState(emptyDraft);
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem("startup-sa-demo-votes")||"[]");if(Array.isArray(v))setVotes(v.filter(x=>typeof x==="string"));const d=JSON.parse(localStorage.getItem("startup-sa-draft")||"null");if(d&&Object.keys(emptyDraft).every(k=>typeof d[k]==="string"))setDraft(d)}catch{}},[]);
 useEffect(()=>{const sync=()=>setSelected(startups.find(s=>s.slug===new URLSearchParams(location.search).get("startup"))||null);sync();addEventListener("popstate",sync);return()=>removeEventListener("popstate",sync)},[startups]);
 useDiscoveryTool(setQuery,setCategory,setCity,setView);
 const hasVoted=(s:Startup)=>s.id?!!s.myVote:votes.includes(s.slug);
 const count=(s:Startup)=>s.votes[Number(period)]+(!s.id&&votes.includes(s.slug)?1:0);
 const shown=startups.filter(s=>(category==="All startups"||s.category===category)&&(city==="all"||s.city===city)&&(view!=="new"||s.age<=7)&&`${s.name} ${s.pitch} ${s.category} ${s.city}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>view==="new"?a.age-b.age:count(b)-count(a));
 async function vote(s:Startup){
   if(s.id){if(!backend.session){profile(null);setAuthOpen(true);return}if(!backend.client||pendingVote||backend.status!=='ready')return;setPendingVote(s.id);try{const {error}=await backend.client.rpc('set_startup_vote',{target_id:s.id,desired_active:!s.myVote});if(error)throw error;await backend.reload()}catch(e){toast.error(e&&typeof e==='object'&&'message' in e?String(e.message):'Your vote could not be saved. Please retry.')}finally{setPendingVote(null)}return}
   const next=votes.includes(s.slug)?votes.filter(x=>x!==s.slug):[...votes,s.slug];setVotes(next);try{localStorage.setItem("startup-sa-demo-votes",JSON.stringify(next))}catch{setNotice("Vote applied for this visit. Device storage is unavailable.")}
 }
 function profile(s:Startup|null){setSelected(s);const url=new URL(location.href);s?url.searchParams.set("startup",s.slug):url.searchParams.delete("startup");history.replaceState(null,"",url)}
 function openSubmit(){if(backend.status==='loading'){toast('Please wait while we connect.');return}if(backend.status==='error'){toast.error('Please retry the connection before submitting.');return}if(backend.client&&!backend.session){setAuthOpen(true);return}setSaved(false);setSubmit(true)}
 async function sendSubmission(){
   if(sending)return;const parsed=submissionSchema.safeParse(draft);if(!parsed.success){toast.error(parsed.error.issues[0].message);return}
   if(!backend.client){try{localStorage.setItem('startup-sa-draft',JSON.stringify(draft));setSaved(true)}catch{toast.error('Could not save this draft.')}return}
   if(!backend.session){setSubmit(false);setAuthOpen(true);return}
   const body=JSON.stringify(parsed.data);if(submissionRequest.current?.body!==body)submissionRequest.current={id:crypto.randomUUID(),body};
   setSending(true);try{const {error}=await backend.client.rpc('submit_startup',{payload:parsed.data,request_id:submissionRequest.current.id});if(error)throw error;setSaved(true);setDraft(emptyDraft);submissionRequest.current=null;try{localStorage.removeItem('startup-sa-draft')}catch{}await backend.reload()}catch(e){toast.error(e&&typeof e==='object'&&'message' in e?String(e.message):'Could not submit. Your details are still here.')}finally{setSending(false)}
 }
 async function share(s:Startup){try{await navigator.clipboard.writeText(`${location.origin}/?startup=${s.slug}`);setNotice("Profile link copied")}catch{setNotice("Copy the profile link from your address bar.")}}
 return <div className="shell"><header><a className="brand" href="/"><span className="brand-symbol"><i/><i/><i/></span>startup<span>sa</span>.</a><span className="beta">EARLY ACCESS</span><nav aria-label="Main navigation"><button className={view==="ranked"?"active":""} onClick={()=>setView("ranked")}>Leaderboard</button><button className={view==="new"?"active":""} onClick={()=>setView("new")}>New launches</button><button onClick={()=>setRules(true)}>How it works</button></nav><button className="account-button" onClick={()=>backend.session?setAccountOpen(true):setAuthOpen(true)}>{backend.session?backend.moderator?'Admin':'My account':'Sign in'}</button><button className="primary header-cta" onClick={openSubmit}><Plus size={16}/> Submit startup</button></header>
 <nav className="categories" aria-label="Startup categories">{categories.map((c,i)=>{const Icon=icons[i];return <button key={c} aria-pressed={category===c} className={category===c?"selected":""} onClick={()=>setCategory(c)}><Icon size={15}/>{c}</button>})}</nav>
 <main><section className="intro"><p className="eyebrow">🇿🇦 &nbsp; BUILT HERE. GOING PLACES.</p><h1>Before everyone <em>knows them.</em></h1><p>Discover what South Africa is building next.<br className="mobile-break"/> Find your favourites. Give them a little lift.</p><div className="intro-actions"><button className="primary" onClick={openSubmit}>Put your startup on the map <ArrowUpRight size={17}/></button><span>Free to list. Built for the underdogs.</span></div></section>
 <div className="board-layout"><section aria-label="Startup leaderboard"><div className="board-heading"><div><h2>{view==="new"?"Fresh off the launchpad":category==="All startups"?"The ones to watch":category}</h2><p>{view==="new"?"New ideas. Meet the latest arrivals.":"Good ideas deserve a head start."}</p></div><span className="edition">VOL. 001 / SEPT ’26</span></div>
 <div className="board-controls"><Tabs value={period} onValueChange={setPeriod}><TabsList aria-label="Ranking time period">{["Today","This week","This month","All time"].map((p,i)=><TabsTrigger key={p} value={String(i)}>{p}</TabsTrigger>)}</TabsList></Tabs><button className="rules-link" onClick={()=>setRules(true)}>How ranks work <ArrowUpRight size={13}/></button></div>
 <div className="filters"><label className="search"><Search size={17}/><input aria-label="Search startups" placeholder="Search startups, ideas, or cities…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery("")}><X size={15}/></button>}</label><Select value={city} onValueChange={setCity}><SelectTrigger aria-label="Filter by city"><MapPin size={14}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All cities</SelectItem>{[...new Set(startups.map(s=>s.city))].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div>
 <div className="list-labels"><span>STARTUP <b>{shown.length}</b></span><span>COMMUNITY VOTES</span></div>{backend.status==='loading'&&<p role="status" className="connection-message">Loading startups…</p>}{backend.status==='error'&&<div role="alert" className="connection-message"><p>{backend.error}</p><button className="secondary" onClick={()=>backend.client?backend.reload():location.reload()}>Retry connection</button></div>}<div className="startup-list">{backend.status!=='error'&&shown.map((s,i)=><article key={s.slug} className={`startup-row rank-${i+1}`}><span className="rank">{String(i+1).padStart(2,"0")}</span><button className="profile-open" aria-label={`View ${s.name} profile`} onClick={()=>profile(s)}><Mark s={s}/><span className="startup-info"><span className="startup-title">{s.name}{s.age<=3&&<span className="new-badge">NEW</span>}</span><span className="pitch">{s.pitch}</span><span className="metadata"><span>{s.category}</span><b>·</b>{s.city}{!s.id&&<><b>·</b><span className="movement">↗ {s.move}</span></>}</span></span></button><button disabled={!!pendingVote} className={`vote ${hasVoted(s)?"voted":""}`} aria-label={`${hasVoted(s)?"Remove vote for":"Upvote"} ${s.name}`} aria-pressed={hasVoted(s)} onClick={()=>vote(s)}><ChevronUp size={19}/><strong>{count(s)}</strong></button></article>)}</div>
 {!shown.length&&['demo','ready'].includes(backend.status)&&<div className="empty"><Search size={28}/><h3>{startups.length?'No startups found':'Be the first on the board.'}</h3><p>{startups.length?'Try another idea, category or city.':'Submit your startup. Approved listings will appear here.'}</p><button className="secondary" onClick={()=>{if(!startups.length){openSubmit();return}setQuery("");setCategory("All startups");setCity("all");setView("ranked")}}>{startups.length?'Clear filters':'Submit your startup'}</button></div>}<p className="demo-note">{backend.status==='demo'?'Preview edition · Fictional sample startups and votes. Your demo votes stay on this device.':'One vote per verified account, per startup. Time windows follow South African time.'}</p></section>
 <aside>{backend.status==='demo'&&<section className="weekly-card"><div className="rail-label"><Trophy size={16}/> IN THE SPOTLIGHT <span>01</span></div><div className="spotlight-brand"><Mark s={demoStartups[0]}/><span>NOVA<small>CAPE TOWN · MOBILITY</small></span></div><h3>Small shops.<br/>Big possibilities.</h3><p>Meet the team putting local retailers in the fast lane.</p><button onClick={()=>profile(demoStartups[0])}>Meet NOVA <ArrowUpRight size={17}/></button><div className="spotlight-bottom"><span>EDITORIAL PICK</span><span>↗</span></div></section>}
 <section className="new-panel"><div className="rail-heading"><h3><Sparkles size={16}/> Just landed</h3><button aria-label="View all new launches" onClick={()=>{setView("new");setCategory("All startups");setQuery("");setCity("all")}}><ArrowRight size={17}/></button></div>{[...startups].sort((a,b)=>a.age-b.age).slice(0,3).map(s=><button className="mini-startup" key={s.slug} onClick={()=>profile(s)}><Mark s={s} small/><span><strong>{s.name}</strong><small>{s.category} · {s.age===1?"Yesterday":`${s.age} days ago`}</small></span><ArrowUpRight size={15}/></button>)}</section>
 <section className="founder-card"><span className="eyebrow">HEY, BUILDERS.</span><h3>Your next supporter<br/>could be right here.</h3><p>Bootstrapped, just launched, or still building. There’s a place for you.</p><button onClick={openSubmit}>Share what you’re building <ArrowRight size={16}/></button></section><p className="rail-footnote">Early &gt; famous.<br/>Community &gt; capital.<br/>Always South African.</p></aside></div></main>
 <footer><a className="brand" href="/">startup<span>sa</span>.</a><p>A little local love goes a long way.</p><button onClick={()=>setRules(true)}>About & rules <ArrowUpRight size={14}/></button><span>Made for 🇿🇦</span></footer>
 <Dialog open={!!selected} onOpenChange={o=>{if(!o)profile(null)}}><DialogContent className="profile-dialog">{selected&&<><Mark s={selected}/><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.pitch}</DialogDescription><div className="profile-facts"><span>{selected.category}</span><span>{selected.city}</span><span>{selected.stage}</span></div><p>{selected.story}</p><dl><div><dt>Founded</dt><dd>{selected.year}</dd></div><div><dt>Founders</dt><dd>{selected.founder}</dd></div><div><dt>Profile status</dt><dd>{selected.id?'Reviewed listing':'Fictional demo'}</dd></div></dl>{selected.website&&<a className="secondary" href={/^https?:\/\//.test(selected.website)?selected.website:undefined} target="_blank" rel="noopener noreferrer">Visit website <ArrowUpRight size={15}/></a>}<div className="dialog-actions"><button disabled={!!pendingVote||backend.status==='error'} className="primary" onClick={()=>vote(selected)}>{hasVoted(selected)?<Check size={17}/>:<ChevronUp size={17}/>} {hasVoted(selected)?"Supported":"Support this startup"} · {count(selected)}</button><button className="secondary" onClick={()=>share(selected)}>Copy profile link <ArrowUpRight size={15}/></button></div></>}</DialogContent></Dialog>
 <Dialog open={rules} onOpenChange={setRules}><DialogContent className="rules-dialog"><DialogTitle>A little lift. A fair shot.</DialogTitle><DialogDescription>Startup SA is for South Africa’s early, overlooked and rising startups.</DialogDescription><h3>How ranks work</h3><p>{backend.status==='demo'?'This preview uses fictional sample totals and device-local votes. Movement figures are illustrative.':'Rankings use votes from email-verified accounts. Each person can support a startup once, and remove their vote at any time. Removing and restoring a vote does not change its original date. Today, this week and this month follow calendar periods in South African time; weeks start on Monday. Ties favour the more recently published startup, then its stable ID.'}</p><h3>Before a startup goes live</h3><p>A moderator checks each submission before it appears on the board. We look for a real website, a South African connection and a clear, honest pitch. Verification of an email does not prove ownership of a company’s domain.</p><h3>Visibility is earned</h3><p>Paid promotion will be labelled separately and will never buy a community rank. Scams, impersonation and spam have no place here. Additional freshness and momentum signals may be added later with an updated explanation.</p></DialogContent></Dialog>
 <Dialog open={submit} onOpenChange={o=>{if(!sending)setSubmit(o)}}><DialogContent className="submission-dialog"><DialogTitle>{saved?backend.client?'Sent for review.':'Your draft is saved.':'Give your startup a head start.'}</DialogTitle><DialogDescription>{backend.client?saved?'Your submission is saved securely. Check My account for its review status.':'Tell us what you’re building. Your listing goes live after a moderator reviews it.':saved?'Saved on this device.':'This preview saves a local draft; it does not publish your listing.'}</DialogDescription>{saved?<button className="primary" onClick={()=>setSubmit(false)}>Back to discovering <ArrowRight size={16}/></button>:<form onSubmit={e=>{e.preventDefault();void sendSubmission()}}><fieldset disabled={sending}><div className="form-grid">{([['name','Startup name','text'],['website','Website','url'],['founder','Founder name','text'],['city','City','text'],['year','Founded year','number']] as const).map(([key,label,type])=><label key={key}>{label}<input required type={type} min={type==='number'?1900:undefined} max={type==='number'?new Date().getFullYear():undefined} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label>Category<Select required value={draft.category} onValueChange={v=>setDraft({...draft,category:v})}><SelectTrigger><SelectValue placeholder="Choose a category"/></SelectTrigger><SelectContent>{categories.slice(1).map(c=><SelectItem value={c} key={c}>{c}</SelectItem>)}</SelectContent></Select></label><label>Stage<Select required value={draft.stage} onValueChange={v=>setDraft({...draft,stage:v})}><SelectTrigger><SelectValue placeholder="Choose a stage"/></SelectTrigger><SelectContent>{['Idea','Building','Launched','Revenue','Growing'].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></label></div><label>One-line pitch<input required minLength={10} maxLength={120} value={draft.pitch} onChange={e=>setDraft({...draft,pitch:e.target.value})}/></label><label>Your story<textarea required minLength={50} maxLength={3000} rows={3} value={draft.story} onChange={e=>setDraft({...draft,story:e.target.value})}/></label></fieldset><button className="primary" disabled={sending} type="submit">{sending?'Submitting…':backend.client?'Submit for review':'Save startup draft'} <ArrowRight size={16}/></button></form>}</DialogContent></Dialog>
 <SignInDialog open={authOpen} onOpenChange={setAuthOpen} client={backend.client}/><AccountDialog open={accountOpen&&!!backend.session} onOpenChange={setAccountOpen} session={backend.session} client={backend.client} items={backend.submissions} moderator={backend.moderator} reload={backend.reload}/>
 <Toaster theme="light" position="bottom-center" closeButton/><Notification message={notice} clear={()=>setNotice("")}/></div>
}
function Notification({message,clear}:{message:string;clear:()=>void}){useEffect(()=>{if(message){toast(message);clear()}},[message,clear]);return null}
