"use client";
import Link from "@/components/site-link";
import {useCallback,useEffect,useRef,useState} from 'react';
import type {Session,SupabaseClient} from '@supabase/supabase-js';
import {getSupabase} from '@/lib/supabase';
import type {SubmissionRecord} from '@/lib/startup-schema';
import {StartupLogo} from '@/components/startup-logo';
import {StartupEdit} from '@/components/startup-edit';
import {SignInDialog} from '@/components/startup-account';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';

export function AccountPage(){
 const [client,setClient]=useState<SupabaseClient|null>(null),[session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[items,setItems]=useState<SubmissionRecord[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[signIn,setSignIn]=useState(false),[emailPending,setEmailPending]=useState(false);
 const generation=useRef({value:0});
 useEffect(()=>{const lifecycle=generation.current;let stopped=false;let unsubscribe=()=>{};void getSupabase().then(async c=>{if(stopped)return;if(!c)throw new Error('Account access is unavailable.');setClient(c);const {data:{subscription}}=c.auth.onAuthStateChange((_event,next)=>{if(!stopped){generation.current.value++;setSession(next);setItems([]);setReady(true)}});unsubscribe=()=>subscription.unsubscribe();const {data}=await c.auth.getSession();if(!stopped){setSession(data.session);setReady(true)}}).catch(()=>{if(!stopped){setError('Could not connect. Reload this page to retry.');setReady(true)}});return()=>{stopped=true;lifecycle.value++;unsubscribe()}},[]);
 const load=useCallback(async()=>{if(!client||!session)return;const current=++generation.current.value;setLoading(true);setError('');try{const {data,error}=await client.from('startup_submissions').select('id,name,website,pitch,story,category,city,stage,founded_year,founder,status,review_note,created_at,logo_path').eq('owner_id',session.user.id).order('created_at',{ascending:false});if(error)throw error;if(current===generation.current.value)setItems((data??[]) as SubmissionRecord[])}catch{if(current===generation.current.value)setError('Could not load your startups. Please retry.')}finally{if(current===generation.current.value)setLoading(false)}},[client,session]);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)void load()});return()=>{active=false}},[load]);
 useEffect(()=>{if(!client||!session)return;let stopped=false;const retry=async()=>{try{const {data}=await client.auth.getSession();const response=await fetch('/api/notifications',{method:'POST',headers:{Authorization:`Bearer ${data.session?.access_token}`}});const result=await response.json() as {pending?:boolean};if(!stopped)setEmailPending(!response.ok||!!result.pending)}catch{if(!stopped)setEmailPending(true)}};void retry();const timer=setInterval(()=>{if(document.visibilityState==='visible')void retry()},60000);return()=>{stopped=true;clearInterval(timer)}},[client,session]);
 const pending=items.filter(item=>item.status==='pending').length,approved=items.filter(item=>item.status==='approved').length,rejected=items.filter(item=>item.status==='rejected').length;
 return <main className="account-page"><header className="account-page-heading"><div><Link href="/">← Startup SA</Link><h1>My account</h1>{session&&<p>{session.user.email}</p>}</div>{session&&<button className="secondary" onClick={async()=>{const result=await client?.auth.signOut();if(result?.error)toast.error('Could not sign out. Please retry.')}}>Sign out</button>}</header>
 {!ready?<p role="status">Connecting…</p>:!session?<section className="account-signin"><h2>Manage your startups</h2><p>Sign in with the email you used to submit your startup.</p><button className="primary" disabled={!client} onClick={()=>setSignIn(true)}>Sign in to My account</button></section>:<>{emailPending&&<p className="account-notice" role="status">Some notification emails are still waiting for delivery. We’ll keep retrying while this page is open.</p>}{error&&<p className="account-notice" role="alert">{error} <button onClick={()=>void load()}>Retry</button></p>}<section className="account-summary" aria-label="Submission summary"><div><strong>{items.length}</strong><span>Total startups</span></div><div><strong>{pending}</strong><span>Awaiting review</span></div><div><strong>{approved}</strong><span>Approved</span></div><div><strong>{rejected}</strong><span>Needs changes</span></div></section><div className="account-section-heading"><div><h2>Your startups</h2><p>Edit details and track each review.</p></div><Link className="primary" href="/submit">Submit another startup</Link></div>{loading?<p role="status">Loading your startups…</p>:!items.length?<section className="account-empty"><h3>No startups submitted yet</h3><p>Submit your startup from the homepage and it will appear here.</p><Link className="primary" href="/submit">Submit a startup</Link></section>:<section className="account-startups">{items.map(item=><article className="account-startup-card" key={item.id}><div className="account-startup-top"><span className="mark"><StartupLogo id={item.id} name={item.name} hasLogo={!!item.logo_path} client={client}/></span><div><h3>{item.name}</h3><p>{item.pitch}</p></div><span className={`status-badge ${item.status}`}>{item.status}</span></div><dl><div><dt>Stage</dt><dd>{item.stage}</dd></div><div><dt>Category</dt><dd>{item.category}</dd></div><div><dt>Location</dt><dd>{item.city}</dd></div><div><dt>Submitted</dt><dd>{new Date(item.created_at).toLocaleDateString()}</dd></div></dl>{item.status==='pending'&&<p className="account-status-copy">This version is awaiting review. If it was already live, the previous approved version remains public.</p>}{item.review_note&&<p className="review-note"><strong>Review note:</strong> {item.review_note}</p>}<div className="account-card-actions"><StartupEdit item={item} client={client} onSaved={load}/><a className="secondary" href={item.website} target="_blank" rel="noopener noreferrer">Visit website ↗</a></div></article>)}</section>}</>}
 <SignInDialog open={signIn} onOpenChange={setSignIn} client={client}/><Toaster theme="light" position="bottom-center" closeButton/></main>
}
