"use client";

import {useCallback,useEffect,useRef,useState} from 'react';
import type {Session,SupabaseClient} from '@supabase/supabase-js';
import {ArrowRight,Building2,CheckCircle2,Clock3,ExternalLink,Inbox,LayoutDashboard,LogOut,Mail,RefreshCw,RotateCcw,Search,ShieldCheck,Trash2,UserRound,Users} from 'lucide-react';
import {getSupabase} from '@/lib/supabase';
import {SignInDialog} from '@/components/startup-account';
import type {SubmissionRecord} from '@/lib/startup-schema';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from '@/components/ui/alert-dialog';
import {Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupContent,SidebarGroupLabel,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuBadge,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger} from '@/components/ui/sidebar';

type PublishedVersion={name:string;website:string;pitch:string;story:string;category:string;city:string;stage:string;founded_year:number;founder:string;logo_path:string|null};
type Item=SubmissionRecord&{deleted_at:string|null;owner_email:string|null;is_update:boolean;has_pending_changes:boolean;published_version:PublishedVersion|null};
type Dashboard={accounts:number;verifiedAccounts:number;items:Item[]};
type Filter='pending'|'approved'|'rejected'|'all'|'trash';
const filterLabels:Record<Filter,string>={pending:'Awaiting review',approved:'Approved',rejected:'Rejected',all:'All submissions',trash:'Trash'};
type ChangeKey=keyof PublishedVersion;
const changeFields:Array<{key:ChangeKey;label:string}>=[{key:'name',label:'Startup name'},{key:'website',label:'Website'},{key:'pitch',label:'Pitch'},{key:'story',label:'Story'},{key:'category',label:'Category'},{key:'city',label:'Location'},{key:'stage',label:'Stage'},{key:'founded_year',label:'Founded year'},{key:'founder',label:'Founder'},{key:'logo_path',label:'Logo'}];
function changeValue(key:ChangeKey,value:string|number|null|undefined,proposed=false){if(key==='logo_path')return value?(proposed?'Replacement logo':'Current logo'):'No logo';return value===null||value===undefined||value===''?'Not provided':String(value)}
function ChangeSummary({item}:{item:Item}){
 if(!item.published_version)return null;
 const changes=changeFields.flatMap(field=>{const before=item.published_version?.[field.key],after=item[field.key];return (before??null)===(after??null)?[]:[{...field,before:changeValue(field.key,before),after:changeValue(field.key,after,true)}]});
 if(!changes.length)return <section className="admin-change-panel"><div className="admin-change-heading"><div><strong>No field differences found</strong><span>The submitted values match the published listing.</span></div></div></section>;
 return <section className="admin-change-panel" aria-label="Changes awaiting approval"><div className="admin-change-heading"><div><strong>Changes awaiting approval</strong><span>Compare the live value with the founder’s proposed value.</span></div><b>{changes.length} {changes.length===1?'field':'fields'} changed</b></div><div className="admin-change-list">{changes.map(change=><article key={change.key} className={`admin-change-row ${change.key==='pitch'||change.key==='story'?'long':''}`}><h4>{change.label}</h4><div className="admin-change-value before"><span>Currently live</span><p>{change.before}</p></div><ArrowRight/><div className="admin-change-value after"><span>Proposed</span><p>{change.after}</p></div></article>)}</div></section>;
}

export function AdminDashboard(){
 const [client,setClient]=useState<SupabaseClient|null>(null),[session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[signIn,setSignIn]=useState(false),[data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState<Filter>('pending'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[notes,setNotes]=useState<Record<string,string>>({}),[trash,setTrash]=useState<Item|null>(null),[lastUpdated,setLastUpdated]=useState<Date|null>(null);
 const generation=useRef(0);
 useEffect(()=>{let stopped=false;let unsubscribe=()=>{};void getSupabase().then(async c=>{if(stopped)return;if(!c)throw new Error('Sign-in is unavailable.');setClient(c);const {data:{subscription}}=c.auth.onAuthStateChange((_event,s)=>{if(!stopped){generation.current++;setSession(s);setData(null);setReady(true)}});unsubscribe=()=>subscription.unsubscribe();const {data}=await c.auth.getSession();if(!stopped){setSession(data.session);setReady(true)}}).catch(()=>{if(!stopped){setError('Could not connect. Reload this page to retry.');setReady(true)}});return()=>{stopped=true;generation.current++;unsubscribe()}},[]);
 const load=useCallback(async(keepExisting=false)=>{if(!session)return;const current=++generation.current;if(!keepExisting)setError('');try{const response=await fetch('/api/admin',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const result=await response.json() as Dashboard&{error?:string};if(!response.ok)throw new Error(result.error);if(current===generation.current){setData(result);setLastUpdated(new Date());setError('')}}catch(cause){if(current===generation.current){if(!keepExisting)setData(null);setError(cause instanceof Error?cause.message:'Could not load dashboard.')}}},[session]);
 useEffect(()=>{void load();if(!session)return;const refresh=()=>{if(document.visibilityState==='visible')void load(true)};const timer=setInterval(refresh,10000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)}},[session,load]);
 async function action(url:string,body:object){if(busy||!client)return false;setBusy(true);setError('');setMessage('');try{const {data}=await client.auth.getSession();const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session?.access_token}`},body:JSON.stringify(body)});const result=await response.json() as {error?:string;emailPending?:boolean;pending?:boolean};if(!response.ok)throw new Error(result.error||'Please try again.');setMessage(result.emailPending||result.pending?'Saved. Some notification emails are still queued; use Retry emails to try again.':'Saved successfully.');await load();return true}catch(cause){setError(cause instanceof Error?cause.message:'Could not save.');return false}finally{setBusy(false)}}
 async function signOut(){const result=await client?.auth.signOut();if(result?.error)setError('Could not sign out. Please retry.')}
 function chooseFilter(next:Filter){setFilter(next);setPage(1);requestAnimationFrame(()=>document.getElementById('review-queue')?.scrollIntoView({behavior:'smooth',block:'start'}))}
 const counts=data?{pending:data.items.filter(item=>!item.deleted_at&&item.status==='pending').length,approved:data.items.filter(item=>!item.deleted_at&&item.status==='approved').length,rejected:data.items.filter(item=>!item.deleted_at&&item.status==='rejected').length,trash:data.items.filter(item=>item.deleted_at).length,active:data.items.filter(item=>!item.deleted_at).length}:null;
 const items=data?.items.filter(item=>(filter==='trash'?!!item.deleted_at:!item.deleted_at&&(filter==='all'||item.status===filter))&&`${item.name} ${item.founder} ${item.city} ${item.owner_email??''}`.toLowerCase().includes(search.toLowerCase()))??[];
 const pages=Math.max(1,Math.ceil(items.length/12)),currentPage=Math.min(page,pages);
 const metrics=data&&counts?[{label:'All accounts',value:data.accounts,detail:'Shared Supabase users',icon:Users},{label:'Email verified',value:data.verifiedAccounts,detail:'Confirmed accounts',icon:ShieldCheck},{label:'Awaiting review',value:counts.pending,detail:'Needs your decision',icon:Clock3},{label:'Approved startups',value:counts.approved,detail:'Published listings',icon:CheckCircle2},{label:'In Trash',value:counts.trash,detail:'Recoverable items',icon:Trash2}]:[];
 return <SidebarProvider className="admin-app">
  <Sidebar collapsible="offcanvas" className="admin-sidebar">
   <SidebarHeader className="admin-sidebar-header"><a className="admin-logo" href="/" aria-label="Startup SA home"><span className="admin-logo-mark">SA</span><span>Startup SA<small>ADMIN</small></span></a></SidebarHeader>
   <SidebarContent>
    <SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>
     <SidebarMenuItem><SidebarMenuButton isActive tooltip="Dashboard"><LayoutDashboard/><span>Dashboard</span></SidebarMenuButton></SidebarMenuItem>
     <SidebarMenuItem><SidebarMenuButton asChild tooltip="Public directory"><a href="/"><Building2/><span>Public directory</span></a></SidebarMenuButton></SidebarMenuItem>
     <SidebarMenuItem><SidebarMenuButton asChild tooltip="My account"><a href="/account"><UserRound/><span>My account</span></a></SidebarMenuButton></SidebarMenuItem>
    </SidebarMenu></SidebarGroupContent></SidebarGroup>
    <SidebarGroup><SidebarGroupLabel>Moderation</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>
     {(['pending','approved','rejected','all','trash'] as Filter[]).map(value=><SidebarMenuItem key={value}><SidebarMenuButton isActive={filter===value} onClick={()=>chooseFilter(value)} tooltip={filterLabels[value]}>{value==='pending'?<Clock3/>:value==='approved'?<CheckCircle2/>:value==='trash'?<Trash2/>:value==='all'?<Inbox/>:<RotateCcw/>}<span>{filterLabels[value]}</span></SidebarMenuButton>{counts&&<SidebarMenuBadge>{value==='all'?counts.active:counts[value]}</SidebarMenuBadge>}</SidebarMenuItem>)}
    </SidebarMenu></SidebarGroupContent></SidebarGroup>
   </SidebarContent>
   <SidebarFooter className="admin-sidebar-footer"><div className="admin-sidebar-note"><ShieldCheck/><div><strong>Admin access</strong><span>{session?.user.email??'Sign in to continue'}</span></div></div></SidebarFooter>
  </Sidebar>
  <SidebarInset className="admin-main">
   <header className="admin-topbar"><div className="admin-topbar-title"><SidebarTrigger/><div><span>Startup SA admin</span><h1>Dashboard</h1></div></div><div className="admin-topbar-actions">{session&&<><button className="admin-icon-button" disabled={busy} onClick={()=>void load()} aria-label="Refresh dashboard" title="Refresh dashboard"><RefreshCw/></button><button className="admin-user-button" onClick={()=>void signOut()}><span className="admin-avatar">{session.user.email?.[0]?.toUpperCase()??'A'}</span><span>{session.user.email}<small>Administrator</small></span><LogOut/></button></>}</div></header>
   <div className="admin-content">
    {error&&<div className="admin-notice" role="alert">{error} {session&&<button onClick={()=>void load()}>Retry dashboard</button>}</div>}{message&&<p role="status" className="admin-notice">{message}</p>}
    {!ready?<section className="admin-state-card"><p role="status">Connecting…</p></section>:!session?<section className="admin-state-card"><div className="admin-state-icon"><ShieldCheck/></div><h2>Administrator sign-in</h2><p>Sign in with your approved administrator email to review and manage Startup SA.</p><button className="primary" disabled={!client} onClick={()=>setSignIn(true)}>Sign in to dashboard</button></section>:!data&&!error?<section className="admin-state-card"><p role="status">Loading dashboard…</p></section>:null}
    {session&&data&&counts&&<><section className="admin-welcome"><div><p className="admin-kicker">Overview</p><h2>Welcome back</h2><p>Review founder submissions and keep the directory current.</p></div><div className="admin-sync"><span></span>Live queue · {lastUpdated?`checked ${lastUpdated.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'connecting'}</div></section>
     <section className="admin-stats" aria-label="Community totals">{metrics.map(({label,value,detail,icon:Icon})=><article key={label} className="admin-stat-card"><div className="admin-stat-icon"><Icon/></div><div><span>{label}</span><strong>{Number(value).toLocaleString()}</strong><small>{detail}</small></div></article>)}</section>
     <p className="admin-data-note">All accounts includes users from the shared Supabase project. Startup moderation never deletes user accounts.</p>
     <section className="admin-workspace" id="review-queue">
      <div className="admin-toolbar"><div><p className="admin-kicker">Moderation</p><h2>{filterLabels[filter]}</h2><p>Review submissions, publish approved changes, or restore archived listings.</p></div><div className="admin-toolbar-actions"><button className="secondary" disabled={busy} onClick={()=>void action('/api/notifications',{})}><Mail/>Retry emails</button><button className="secondary" disabled={busy} onClick={()=>void load()}><RefreshCw/>Refresh</button></div></div>
      <div className="admin-filters"><div className="admin-filter-tabs" role="group" aria-label="Filter submissions">{(['pending','approved','rejected','all','trash'] as Filter[]).map(value=><button key={value} className={filter===value?'active':''} onClick={()=>chooseFilter(value)}>{filterLabels[value]}</button>)}</div><label className="admin-search"><Search/><span className="sr-only">Search submissions</span><input type="search" placeholder="Search startup, founder or city" value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}}/></label><span className="admin-result-count">{items.length} {items.length===1?'result':'results'}</span></div>
      <div className="admin-submission-list">{!items.length?<div className="admin-empty"><Inbox/><h3>Nothing here right now</h3><p>No submissions match this view or search.</p></div>:items.slice((currentPage-1)*12,currentPage*12).map(item=><article className="admin-item" key={item.id}>
       <div className="admin-item-heading"><div className="admin-startup-identity"><span>{item.name.slice(0,2).toUpperCase()}</span><div><h3>{item.name}</h3><p>{item.pitch}</p></div></div><span className={`status-badge ${item.status}`}>{item.deleted_at?'In Trash':item.status==='pending'&&item.is_update?'Update pending':item.status}</span></div>
       {item.status==='pending'&&item.is_update&&!item.deleted_at&&<><p className="admin-update-note"><RefreshCw/>Edited listing—the previous approved version stays live until these changes are approved.</p><ChangeSummary item={item}/></>}
       <div className="admin-meta-grid"><div><span>Registered by</span><strong>{item.owner_email||'Email unavailable'}</strong></div><div><span>Founder</span><strong>{item.founder}</strong></div><div><span>Location</span><strong>{item.city}</strong></div><div><span>Category</span><strong>{item.category}</strong></div><div><span>Stage</span><strong>{item.stage}</strong></div><div><span>Submitted</span><strong>{new Date(item.created_at).toLocaleDateString()}</strong></div></div>
       <details className="admin-details"><summary>View full submission</summary><div><p className="admin-story">{item.story}</p><p>Founded {item.founded_year}</p>{/^https?:\/\//.test(item.website)&&<a href={item.website} target="_blank" rel="noopener noreferrer">Visit website <ExternalLink/></a>}{item.review_note&&<p><strong>Review note:</strong> {item.review_note}</p>}</div></details>
       {!item.deleted_at&&item.status==='pending'&&<label className="admin-note">Review note <span>Required when rejecting</span><textarea maxLength={1000} value={notes[item.id]??''} onChange={event=>setNotes({...notes,[item.id]:event.target.value})} placeholder="Add clear feedback for the founder…"/></label>}
       <div className="admin-actions">{!item.deleted_at&&item.status==='pending'&&<><button className="primary" disabled={busy} onClick={()=>void action('/api/reviews',{submission_id:item.id,decision:'approved',note:notes[item.id]??''})}><CheckCircle2/>Approve & publish</button><button className="secondary" disabled={busy||(notes[item.id]??'').trim().length<5} onClick={()=>void action('/api/reviews',{submission_id:item.id,decision:'rejected',note:notes[item.id]})}>Reject submission</button></>}{item.deleted_at?<button className="secondary" disabled={busy} onClick={()=>void action('/api/admin',{submission_id:item.id,restore:true})}><RotateCcw/>Restore startup</button>:<button className="secondary admin-danger" disabled={busy} onClick={()=>setTrash(item)}><Trash2/>Move to Trash</button>}</div>
      </article>)}</div>
      {!!items.length&&<nav className="admin-pagination" aria-label="Submission pages"><button className="secondary" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}>Previous</button><span>Page {currentPage} of {pages}</span><button className="secondary" disabled={currentPage>=pages} onClick={()=>setPage(currentPage+1)}>Next</button></nav>}
     </section></>}
   </div>
  </SidebarInset>
  <SignInDialog open={signIn} onOpenChange={setSignIn} client={client}/><AlertDialog open={!!trash} onOpenChange={open=>{if(!open&&!busy)setTrash(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Move {trash?.name} to Trash?</AlertDialogTitle><AlertDialogDescription>This removes the startup from the public directory and voting. Its submission and votes are kept, and you can restore it from Trash. No user account is deleted.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async event=>{event.preventDefault();if(trash&&await action('/api/admin',{submission_id:trash.id,restore:false}))setTrash(null)}}>{busy?'Saving…':'Move to Trash'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>;
}
