"use client";
import {useEffect,useState,useCallback,useRef} from 'react';
import type {Session,SupabaseClient} from '@supabase/supabase-js';
import {getSupabase} from '@/lib/supabase';
import {SignInDialog} from '@/components/startup-account';
import type {SubmissionRecord} from '@/lib/startup-schema';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogHeader,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
type Item=SubmissionRecord&{deleted_at:string|null};
type Dashboard={accounts:number;verifiedAccounts:number;items:Item[]};
export function AdminDashboard(){
 const [client,setClient]=useState<SupabaseClient|null>(null),[session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[signIn,setSignIn]=useState(false),[data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('pending'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[notes,setNotes]=useState<Record<string,string>>({}),[trash,setTrash]=useState<Item|null>(null);
 const generation=useRef(0);
 useEffect(()=>{let stopped=false;let unsubscribe=()=>{};void getSupabase().then(async c=>{if(stopped)return;if(!c)throw new Error('Sign-in is unavailable.');setClient(c);const {data:{subscription}}=c.auth.onAuthStateChange((_event,s)=>{if(!stopped){generation.current++;setSession(s);setData(null);setReady(true)}});unsubscribe=()=>subscription.unsubscribe();const {data}=await c.auth.getSession();if(!stopped){setSession(data.session);setReady(true)}}).catch(()=>{if(!stopped){setError('Could not connect. Reload this page to retry.');setReady(true)}});return()=>{stopped=true;generation.current++;unsubscribe()}},[]);
 const load=useCallback(async()=>{if(!session)return;const current=++generation.current;setError('');try{const r=await fetch('/api/admin',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const result=await r.json() as Dashboard&{error?:string};if(!r.ok)throw new Error(result.error);if(current===generation.current)setData(result)}catch(e){if(current===generation.current){setData(null);setError(e instanceof Error?e.message:'Could not load dashboard.')}}},[session]);
 useEffect(()=>{void load()},[load]);
 async function action(url:string,body:object){if(busy||!client)return false;setBusy(true);setError('');setMessage('');try{const {data}=await client.auth.getSession();const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session?.access_token}`},body:JSON.stringify(body)});const result=await r.json() as {error?:string;emailPending?:boolean;pending?:boolean};if(!r.ok)throw new Error(result.error||'Please try again.');setMessage(result.emailPending||result.pending?'Saved. Some notification emails are still queued; use Retry emails to try again.':'Saved successfully.');await load();return true}catch(e){setError(e instanceof Error?e.message:'Could not save.');return false}finally{setBusy(false)}}
 const counts=data?{pending:data.items.filter(i=>!i.deleted_at&&i.status==='pending').length,approved:data.items.filter(i=>!i.deleted_at&&i.status==='approved').length,rejected:data.items.filter(i=>!i.deleted_at&&i.status==='rejected').length,trash:data.items.filter(i=>i.deleted_at).length}:null;
 const items=data?.items.filter(i=>(filter==='trash'?!!i.deleted_at:!i.deleted_at&&(filter==='all'||i.status===filter))&&`${i.name} ${i.founder} ${i.city}`.toLowerCase().includes(search.toLowerCase()))??[];
 const pages=Math.max(1,Math.ceil(items.length/12)),currentPage=Math.min(page,pages);
 return <main className="admin-page"><header className="admin-heading"><div><a href="/">← Startup SA</a><h1>Admin dashboard</h1><p>Review submissions and manage the community.</p></div>{session&&<button className="secondary" onClick={async()=>{const r=await client?.auth.signOut();if(r?.error)setError('Could not sign out. Please retry.')}}>Sign out</button>}</header>
 {error&&<div className="admin-notice" role="alert">{error} {session&&<button onClick={()=>void load()}>Retry dashboard</button>}</div>}{message&&<p role="status" className="admin-notice">{message}</p>}
 {!ready?<p role="status">Connecting…</p>:!session?<section className="admin-empty"><h2>Administrator sign-in</h2><p>Sign in with your approved administrator email to continue.</p><button className="primary" disabled={!client} onClick={()=>setSignIn(true)}>Sign in</button></section>:!data&&!error?<p role="status">Loading dashboard…</p>:null}
 {session&&data&&counts&&<><section className="admin-stats" aria-label="Community totals">{[[data.accounts,'All accounts'],[data.verifiedAccounts,'Email verified'],[counts.pending,'Awaiting review'],[counts.approved,'Approved startups'],[counts.trash,'In Trash']].map(([count,label])=><div key={label}><strong>{Number(count).toLocaleString()}</strong><span>{label}</span></div>)}</section><p className="admin-caption">All accounts includes every account in the shared Supabase project, including finance-app users. No user accounts are deleted here.</p>
 <section className="admin-workspace"><div className="admin-toolbar"><h2>Startups & submissions</h2><div><button className="secondary" disabled={busy} onClick={()=>void load()}>Refresh</button><button className="secondary" disabled={busy} onClick={()=>void action('/api/notifications',{})}>Retry emails</button></div></div><div className="admin-filters"><label>View<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}>{['pending','approved','rejected','all','trash'].map(f=><option key={f} value={f}>{f==='pending'?'Awaiting review':f==='all'?'All active submissions':f[0].toUpperCase()+f.slice(1)}</option>)}</select></label><label>Search<input type="search" placeholder="Startup, founder or city" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><span>{items.length} results</span></div>
 {!items.length?<p className="admin-empty">No submissions match this view.</p>:items.slice((currentPage-1)*12,currentPage*12).map(item=><article className="admin-item" key={item.id}><div className="admin-item-heading"><div><h3>{item.name}</h3><p>{item.pitch}</p></div><span className={`status-badge ${item.status}`}>{item.deleted_at?'In Trash':item.status}</span></div><p className="admin-caption">{item.founder} · {item.city} · {item.category} · {new Date(item.created_at).toLocaleDateString()}</p><details><summary>View full submission</summary><p className="admin-story">{item.story}</p><p>{item.stage} · Founded {item.founded_year}</p><a href={/^https?:\/\//.test(item.website)?item.website:undefined} target="_blank" rel="noopener noreferrer">Visit website ↗</a>{item.review_note&&<p>Review note: {item.review_note}</p>}</details>{!item.deleted_at&&item.status==='pending'&&<label className="admin-note">Review note (required when rejecting)<textarea maxLength={1000} value={notes[item.id]??''} onChange={e=>setNotes({...notes,[item.id]:e.target.value})}/></label>}<div className="admin-actions">{!item.deleted_at&&item.status==='pending'&&<><button className="primary" disabled={busy} onClick={()=>void action('/api/reviews',{submission_id:item.id,decision:'approved',note:notes[item.id]??''})}>Approve & publish</button><button className="secondary" disabled={busy||(notes[item.id]??'').trim().length<5} onClick={()=>void action('/api/reviews',{submission_id:item.id,decision:'rejected',note:notes[item.id]})}>Reject</button></>}{item.deleted_at?<button className="secondary" disabled={busy} onClick={()=>void action('/api/admin',{submission_id:item.id,restore:true})}>Restore startup</button>:<button className="secondary admin-danger" disabled={busy} onClick={()=>setTrash(item)}>Move to Trash</button>}</div></article>)}<nav className="admin-pagination" aria-label="Submission pages"><button className="secondary" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}>Previous</button><span>Page {currentPage} of {pages}</span><button className="secondary" disabled={currentPage>=pages} onClick={()=>setPage(currentPage+1)}>Next</button></nav></section></>}
 <SignInDialog open={signIn} onOpenChange={setSignIn} client={client}/><AlertDialog open={!!trash} onOpenChange={open=>{if(!open&&!busy)setTrash(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Move {trash?.name} to Trash?</AlertDialogTitle><AlertDialogDescription>This removes the startup from the public directory and voting. Its submission and votes are kept, and you can restore it from Trash. No user account is deleted.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(trash&&await action('/api/admin',{submission_id:trash.id,restore:false}))setTrash(null)}}>{busy?'Saving…':'Move to Trash'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
