import Link from '@/components/site-link';
import {siteConfig} from '@/lib/site-config';
export function LegalPage({kind}:{kind:'privacy'|'terms'}){
 const config=siteConfig();
 return <main className="legal-page"><Link className="detail-back" href="/">← StartupsAfrica</Link><p className="eyebrow">STARTUPSAFRICA · LAST UPDATED 26 SEPTEMBER 2026</p><h1>{kind==='privacy'?'Privacy policy':'Terms & conditions'}</h1>{(!config.legalName||!config.contact)&&<p className="legal-draft" role="note">Draft for launch review. The operator’s legal identity and contact details must be completed before public launch.</p>}
 <p>{config.legalName?`StartupsAfrica is operated by ${config.legalName}.`:'StartupsAfrica is a directory for discovering and supporting South African startups.'} {config.contact&&<>Contact: <a href={`mailto:${config.contact}`}>{config.contact}</a>.</>}</p>
 {kind==='privacy'?<>
 <h2>What we collect and why</h2><p>We process your email address and authentication records to sign you in, protect your account and send requested sign-in codes. When you submit a startup, we store the listing details, founder name, optional logo, review history and notification delivery status to manage the submission and moderation process. Providing account and listing information is voluntary, but we cannot offer the corresponding features without it.</p>
 <h2>What becomes public</h2><p>Approved listings display the startup name, website, pitch, story, category, city, stage, founding year, founder name and logo. Account email addresses, pending submissions and private moderation notes are not part of the public directory. Moderators can access submissions and their submitter’s account email to manage reviews. Do not include confidential or sensitive personal information in a listing.</p>
 <h2>Cookies and device storage</h2><p>The startup_sa_voter cookie lasts up to one year and supports one vote per startup per browser. It is signed, HttpOnly and SameSite=Lax. Signing in stores a Supabase session in your browser until you sign out or the session expires. Saved draft details and preview votes may remain in local storage until you remove them or clear your browser data.</p><p>When configured, PostHog measures visits to public pages and selected actions: opening the submission flow, voting for a startup, and visiting a startup website. It also records interactions and visible page content on public pages so we can understand how visitors use the site. Account, submission and admin pages are excluded, as is the sign-in dialog. Input values are masked, and recording does not include network request contents. Analytics strips URL query strings and fragments and does not send form contents, email addresses or account IDs as event properties. Automatic click capture is disabled. PostHog uses temporary browser storage to group events into a replay and does not retain a persistent analytics identity on your device. Essential storage supports requested sign-in and voting features; your browser can block or remove it, which may prevent those features working.</p>
 <h2>Service providers and shared authentication</h2><p>Vercel and Cloudflare provide hosting infrastructure, Supabase provides authentication, database and private file storage, Resend delivers transactional emails, and PostHog provides public-page analytics when configured. StartupsAfrica currently shares a Supabase identity directory with the operator’s FinanceAPP project. StartupsAfrica listing permissions remain separate; moderators can see aggregate shared-account counts. These providers may process information outside South Africa. Their terms and privacy notices describe their processing practices. Contact us for information about applicable processing locations and transfer arrangements.</p>
 <h2>Security and retention</h2><p>We use access controls and server-side permission checks to restrict private information. Voting and sign-in abuse controls store keyed hashes rather than raw network addresses in application rate-limit tables; those rows are removed after 24 hours when the relevant limiter next runs. Infrastructure providers may retain their own security logs. Listings, review history, account records and email delivery markers are retained while needed to operate the service, resolve disputes or meet legal obligations. We review retention needs and handle verified deletion requests, subject to legal and operational requirements. Recoverable trash does not permanently erase a record.</p>
 <h2>Your choices and rights</h2><p>You may request access to, correction of or deletion of your personal information, or object to processing where applicable. Contact {config.contact?<a href={`mailto:${config.contact}`}>{config.contact}</a>:'the operator using the contact details to be added before public launch'}; we may ask for proportionate verification of your identity. Shared authentication means account deletion needs to account for other services using that identity. You can also contact South Africa’s <a href="https://inforegulator.org.za/contact-us/" target="_blank" rel="noopener noreferrer">Information Regulator</a> about a privacy complaint.</p>
 <h2>Updates</h2><p>We will update this page when our practices change and provide additional notice for material changes where appropriate.</p>
 </>:<>
 <h2>Using StartupsAfrica</h2><p>StartupsAfrica helps people discover startups. Use the service lawfully and provide accurate information. You must be authorised to submit the listing and its content, including the founder details and logo. Do not impersonate another person or business, submit unlawful or misleading content, upload malicious files or manipulate votes.</p>
 <h2>Your account</h2><p>Keep sign-in codes private and use an email address you control. You are responsible for activity you authorise through your account. Contact the operator if you suspect unauthorised access.</p>
 <h2>Listings and moderation</h2><p>Submissions and edits require moderation. Approval means a listing has been reviewed; it does not certify company ownership, legal compliance, product quality or investment suitability. We may reject, hide or remove listings that breach these terms or present a risk to users. Edits to published listings leave the previous approved version live until the changes are approved.</p>
 <h2>Your content</h2><p>You retain your rights to your content. By submitting it, you permit us to store, resize, review and display it as needed to operate and promote your listing within StartupsAfrica. You confirm that you have the necessary permissions. Contact us about corrections, removal requests or suspected infringement.</p>
 <h2>Voting and ranking</h2><p>Voting is limited by browser identity, not verified individual identity. Rankings use vote totals in the selected South African calendar period. We may apply abuse controls, investigate manipulation and correct errors. A ranking is not an endorsement or a promise of commercial success.</p>
 <h2>Third-party websites</h2><p>Startup websites are operated independently. Review their terms and privacy practices before sharing information or making purchases. StartupsAfrica does not act as a party to transactions between you and a listed business.</p>
 <h2>Availability and responsibility</h2><p>We aim to keep the directory accurate and available, but cannot guarantee uninterrupted service or verify every claim made by a startup. Nothing in these terms excludes liability or rights that cannot lawfully be excluded, including applicable consumer rights. South African law applies, subject to mandatory laws protecting you.</p>
 <h2>Contact and changes</h2><p>For support, content reports or disputes, contact {config.contact?<a href={`mailto:${config.contact}`}>{config.contact}</a>:'the operator using the contact details to be completed before launch'}. We may update these terms and will identify the latest revision date on this page.</p>
 </>}
 </main>;
}
