"use client";
import {useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {submissionSchema,type SubmissionRecord} from '@/lib/startup-schema';
import {toast} from 'sonner';
const categories=['Fintech','AI','SaaS','Climate / Energy','Health','Education','Commerce','Mobility','AgriTech','Developer Tools','Other'] as const;
const stages=['Idea','Building','Launched','Revenue','Growing'] as const;
export function StartupEdit({item,client,onSaved}:{item:SubmissionRecord;client:SupabaseClient|null;onSaved:()=>Promise<void>}){
 const initial=()=>({name:item.name,website:item.website,pitch:item.pitch,story:item.story,category:item.category,city:item.city,stage:item.stage,year:String(item.founded_year),founder:item.founder});
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[draft,setDraft]=useState(initial);
 useEffect(()=>{if(open)setDraft(initial())},[open,item]);
 async function save(){if(!client||busy)return;const parsed=submissionSchema.safeParse(draft);if(!parsed.success){toast.error(parsed.error.issues[0].message);return}setBusy(true);try{const {data}=await client.auth.getSession();const response=await fetch('/api/submissions',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session?.access_token}`},body:JSON.stringify({submission_id:item.id,payload:parsed.data})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Could not save your changes.');toast.success('Changes sent for review.');setOpen(false);await onSaved()}catch(error){toast.error(error instanceof Error?error.message:'Could not save your changes.')}finally{setBusy(false)}}
 return <><button className="secondary" onClick={()=>setOpen(true)}>Edit startup</button><Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value)}}><DialogContent className="submission-dialog account-dialog"><DialogTitle>Edit {item.name}</DialogTitle><DialogDescription>Your changes will be reviewed. If this startup is already live, its current approved version stays visible until the update is approved.</DialogDescription><form onSubmit={event=>{event.preventDefault();void save()}}><fieldset disabled={busy}><div className="form-grid">{([['name','Startup name','text'],['website','Website','url'],['founder','Founder name','text'],['city','City','text'],['year','Founded year','number']] as const).map(([key,label,type])=><label key={key}>{label}<input required type={type} min={type==='number'?1900:undefined} max={type==='number'?new Date().getFullYear():undefined} value={draft[key]} onChange={event=>setDraft({...draft,[key]:event.target.value})}/></label>)}<label>Category<Select required value={draft.category} onValueChange={value=>setDraft({...draft,category:value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{categories.map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></label><label>Stage<Select required value={draft.stage} onValueChange={value=>setDraft({...draft,stage:value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{stages.map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></label></div><label>One-line pitch<input required minLength={10} maxLength={120} value={draft.pitch} onChange={event=>setDraft({...draft,pitch:event.target.value})}/></label><label>Your story<textarea required minLength={50} maxLength={3000} rows={5} value={draft.story} onChange={event=>setDraft({...draft,story:event.target.value})}/></label></fieldset><div className="dialog-actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Submit changes for review'}</button><button className="secondary" type="button" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button></div></form></DialogContent></Dialog></>
}
