"use client";
import Link from '@/components/site-link';
import {useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
import {toast} from 'sonner';

export function SignInDialog({open,onOpenChange,client}:{open:boolean;onOpenChange:(value:boolean)=>void;client:SupabaseClient|null}){
 const [website,setWebsite]=useState(''),[email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(){if(!client)return;setBusy(true);setError('');try{const response=await fetch('/api/auth/email-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.trim(),website})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Could not send a code.');setSent(true)}catch(e){setError(e instanceof Error?e.message:'Could not send a code. Please retry.')}finally{setBusy(false)}}
 async function verify(){if(!client)return;setBusy(true);setError('');try{const result=await client.auth.verifyOtp({email:email.trim(),token:code,type:'email'});if(result.error)throw result.error;toast.success('You’re signed in.');onOpenChange(false);setCode('');setSent(false)}catch{setError('That code is invalid or expired. Please check it or request a new one.')}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="submission-dialog"><DialogTitle>{sent?'Check your inbox':'Your next favourite starts here.'}</DialogTitle><DialogDescription>{!client?'Sign-in opens when the community launches. You can explore the preview for now.':sent?`Enter the six-digit code sent to ${email}.`:'Sign in with your email to submit a startup or manage your submissions. Voting needs no account.'}</DialogDescription>{client&&<form onSubmit={e=>{e.preventDefault();void(sent?verify():send())}}><label className="honeypot" aria-hidden="true">Leave empty<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label>{sent?<><label htmlFor="signin-code">Email code</label><InputOTP id="signin-code" maxLength={6} value={code} onChange={setCode} pattern="^[0-9]+$" autoComplete="one-time-code"><InputOTPGroup>{Array.from({length:6},(_,i)=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP></>:<label>Email address<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}<p className="form-legal">Sign-in uses your email to create or access your account. <Link href="/privacy">Privacy policy</Link> · <Link href="/terms">Terms & conditions</Link></p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy||(sent&&code.length!==6)}>{busy?'Please wait…':sent?'Verify and sign in':'Email me a code'}</button>{sent&&<button type="button" className="secondary" disabled={busy} onClick={()=>{setSent(false);setCode('');setError('')}}>Change email or request a new code</button>}</form>}</DialogContent></Dialog>
}
