"use client";
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpRight,ChevronUp,Check} from 'lucide-react';
import {useStartupBackend} from '@/hooks/use-startup-backend';
import {SignInDialog,AccountDialog} from '@/components/startup-account';
import {StartupLogo} from '@/components/startup-logo';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
export function StartupPage({slug}:{slug:string}){
 const backend=useStartupBackend();const [auth,setAuth]=useState(false),[account,setAccount]=useState(false),[busy,setBusy]=useState(false);
 const item=backend.records.find(s=>s.slug===slug);
 useEffect(()=>{if(item)document.title=`${item.name} — Startup SA`},[item]);
 async function vote(){if(!item||!backend.client||busy)return;setBusy(true);try{await backend.vote(item.id,!item.my_vote)}catch(error){toast.error(error instanceof Error?error.message:'Could not save your vote. Please retry.')}finally{setBusy(false)}}
 return <div className="shell"><header><a className="brand" href="/">startup<span>sa</span>.</a><button className="account-button" style={{marginLeft:'auto'}} onClick={()=>backend.session?(backend.moderator?location.assign('/admin'):setAccount(true)):setAuth(true)}>{backend.session?backend.moderator?'Admin':'My account':'Sign in'}</button></header><main className="startup-detail"><a className="detail-back" href="/"><ArrowLeft size={16}/> Back to startups</a>{backend.status==='loading'?<p role="status">Loading startup…</p>:backend.status==='error'?<div role="alert"><p>{backend.error}</p><button className="secondary" onClick={()=>backend.reload()}>Retry</button></div>:!item?<><h1>Startup not found</h1><p>This listing isn’t published or is no longer available.</p></>:<><div className="detail-title"><span className="mark"><StartupLogo id={item.id} name={item.name} hasLogo={!!item.logo_path}/></span><div><p className="detail-label">{item.category} · {item.city}</p><h1>{item.name}</h1></div></div><p className="detail-pitch">{item.pitch}</p><div className="dialog-actions"><button className="primary" disabled={busy} onClick={vote}>{item.my_vote?<Check size={17}/>:<ChevronUp size={17}/>} {item.my_vote?'Supported':'Support this startup'} · {item.total_votes}</button><a className="secondary" href={/^https?:\/\//.test(item.website)?item.website:undefined} target="_blank" rel="noopener noreferrer">Visit website <ArrowUpRight size={16}/></a><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);toast.success('Profile link copied.')}catch{toast.error('Copy the link from your address bar.')}}}>Copy link</button></div><section className="detail-story"><h2>About {item.name}</h2><p>{item.story}</p></section><dl className="detail-facts"><div><dt>Founder</dt><dd>{item.founder}</dd></div><div><dt>Founded</dt><dd>{item.founded_year}</dd></div><div><dt>Stage</dt><dd>{item.stage}</dd></div><div><dt>Listing</dt><dd>Reviewed listing</dd></div></dl></>}</main><SignInDialog open={auth} onOpenChange={setAuth} client={backend.client}/><AccountDialog open={account} onOpenChange={setAccount} session={backend.session} client={backend.client} items={backend.submissions} moderator={backend.moderator} reload={backend.reload}/><Toaster/></div>;
}
