"use client";
import {useEffect,useState} from 'react';
import type {SupabaseClient,Session} from '@supabase/supabase-js';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
import {toast} from 'sonner';
import {StartupLogo} from '@/components/startup-logo';
import type {SubmissionRecord} from '@/lib/startup-schema';
import {StartupEdit} from '@/components/startup-edit';

export function SignInDialog({open,onOpenChange,client}:{open:boolean;onOpenChange:(value:boolean)=>void;client:SupabaseClient|null}){
  const [email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function send(){if(!client)return;setBusy(true);setError('');try{const response=await fetch('/api/auth/email-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.trim()})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Could not send a code.');setSent(true)}catch(e){setError(e instanceof Error?e.message:'Could not send a code. Please retry.')}finally{setBusy(false)}}
  async function verify(){if(!client)return;setBusy(true);setError('');try{const result=await client.auth.verifyOtp({email:email.trim(),token:code,type:'email'});if(result.error)throw result.error;toast.success('You’re signed in.');onOpenChange(false);setCode('');setSent(false)}catch{setError('That code is invalid or expired. Please check it or request a new one.')}finally{setBusy(false)}}
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="submission-dialog"><DialogTitle>{sent?'Check your inbox':'Your next favourite starts here.'}</DialogTitle><DialogDescription>{!client?'Sign-in opens when the community launches. You can explore the preview for now.':sent?`Enter the six-digit code sent to ${email}.`:'Sign in with your email to submit a startup or manage your submissions. Voting needs no account.'}</DialogDescription>{client&&<form onSubmit={e=>{e.preventDefault();void(sent?verify():send())}}>{sent?<><label htmlFor="signin-code">Email code</label><InputOTP id="signin-code" maxLength={6} value={code} onChange={setCode} pattern="^[0-9]+$" autoComplete="one-time-code"><InputOTPGroup>{Array.from({length:6},(_,i)=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP></>:<label>Email address<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy||(sent&&code.length!==6)}>{busy?'Please wait…':sent?'Verify and sign in':'Email me a code'}</button>{sent&&<button type="button" className="secondary" disabled={busy} onClick={()=>{setSent(false);setCode('');setError('')}}>Change email or request a new code</button>}</form>}</DialogContent></Dialog>
}

export function AccountDialog({open,onOpenChange,session,client,items,moderator,reload}:{open:boolean;onOpenChange:(value:boolean)=>void;session:Session|null;client:SupabaseClient|null;items:SubmissionRecord[];moderator:boolean;reload:()=>Promise<void>}){
  const [notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState<string|null>(null),[queue,setQueue]=useState(false);
  const [emailPending,setEmailPending]=useState(false);
  useEffect(()=>{if(!open||!client||!session)return;let stopped=false;
    const retry=async()=>{try{const {data}=await client.auth.getSession();const r=await fetch('/api/notifications',{method:'POST',headers:{Authorization:`Bearer ${data.session?.access_token}`}});const result=await r.json() as {error?:string;pending?:boolean;emailPending?:boolean};if(!stopped)setEmailPending(!r.ok||!!result.pending)}catch{if(!stopped)setEmailPending(true)}};
    void retry();const timer=setInterval(()=>{if(document.visibilityState==='visible')void retry()},60000);return()=>{stopped=true;clearInterval(timer)};
  },[open,client,session]);
  async function review(id:string,decision:'approved'|'rejected'){
    if(!client||busy)return;const note=notes[id]||'';
    if(decision==='rejected'&&note.trim().length<5){toast.error('Add a short reason for the founder.');return}
    setBusy(id);try{const {data:auth}=await client.auth.getSession();const r=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth.session?.access_token}`},body:JSON.stringify({submission_id:id,decision,note})});const result=await r.json() as {error?:string;pending?:boolean;emailPending?:boolean};if(!r.ok)throw new Error(result.error||'Could not save review.');setEmailPending(!!result.emailPending);toast.success(decision==='approved'?'Startup approved and published. The founder’s email has been queued.':'Submission returned to the founder.');await reload()}catch(e){toast.error(e&&typeof e==='object'&&'message' in e?String(e.message):'Could not review this submission. Please retry.')}finally{setBusy(null)}
  }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="account-dialog"><DialogTitle>{moderator&&queue?'Review submissions':'Your startup account'}</DialogTitle><DialogDescription>{session?.user.email||'Sign in to manage your submissions.'}</DialogDescription>{emailPending&&<p role="status" className="review-note">Some notification emails are waiting for delivery. We’ll retry while this account window is open; you can also reopen it later.</p>}{moderator&&<div className="dialog-actions"><button className="secondary" onClick={()=>setQueue(!queue)}>{queue?'View submission history':`Review queue (${items.filter(i=>i.status==='pending').length})`}</button></div>}{(queue?items.filter(i=>i.status==='pending'):items).map(item=><article className="submission-item" key={item.id}><div className="submission-item-title">{item.logo_path&&<span className="mark small"><StartupLogo id={item.id} name={item.name} hasLogo client={client}/></span>}<h3>{item.name}</h3><span className={`status-badge ${item.status}`}>{item.status}</span></div><p>{item.pitch}</p><p className="submission-meta">{item.category} · {item.city} · {item.stage} · Founded {item.founded_year}</p>{!queue&&<div className="dialog-actions"><StartupEdit item={item} client={client} onSaved={reload}/></div>}{queue&&<><p>{item.story}</p><p>Founder: {item.founder}</p><a href={/^https?:\/\//.test(item.website)?item.website:undefined} target="_blank" rel="noopener noreferrer">Visit submitted website ↗</a><label>Review note<textarea maxLength={1000} value={notes[item.id]||''} onChange={e=>setNotes({...notes,[item.id]:e.target.value})}/></label><div className="dialog-actions"><button disabled={!!busy} className="primary" onClick={()=>review(item.id,'approved')}>{busy===item.id?'Saving…':'Approve & publish'}</button><button disabled={!!busy} className="secondary" onClick={()=>review(item.id,'rejected')}>Reject with reason</button></div></>}{item.review_note&&<p className="review-note">Review note: {item.review_note}</p>}</article>)}{!(queue?items.filter(i=>i.status==='pending'):items).length&&<p>{queue?'No submissions are waiting for review.':'Your submitted startups will appear here with their review status.'}</p>}<button className="secondary" disabled={!!busy} onClick={async()=>{const result=await client?.auth.signOut();if(result?.error)toast.error('Could not sign out. Please retry.');else onOpenChange(false)}}>Sign out</button></DialogContent></Dialog>
}
